### ISSUE TITLE
Compilation fails with Go v1.19

### ISSUE THREAD

**Issue by rot1024** [reearth/reearthx#1]
`idx` package repports errors

**Comment by KeisukeYamashita** [comment]
# Investigation

## Reproduce

### With `Go 1.19`

```console
go version go1.19 darwin/arm64
```

```console
$ go run ./cmd/reearth/main.go
# github.com/reearth/reearth-backend/pkg/id
pkg/id/idx/list.go:13:20: internal compiler error: method Type on struct {} not found

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
```

### With Go 1.18

After installing `go@1.18` with HomeBrew, I ran this command.

```console
$ /opt/homebrew/Cellar/go@1.18/1.18.5/bin/go version go1.18.5 darwin/arm64
```

```console
$ /opt/homebrew/Cellar/go@1.18/1.18.5/bin/go run ./cmd/reearth/main.go
# command-line-arguments
cmd/reearth/main.go:8:12: undefined: debug
```

Looks good with Go 1.18.

## Investigate Go 1.19 generic changes

TODO

**Comment by mdempsky** [comment]
Hi, I work on the Go compiler, and I saw this issue mentioned on golang/go#54225. However, I'm not able to reproduce the build failure. Is your project still failing to build with Go 1.19.1?

**Comment by KeisukeYamashita** [comment]
@mdempsky Sorry for the late reply. With Go `1.19.1`, it worked well 👍  Thank you for your great work!
